export default {
  login: 'Sign In',
  signup: 'Sign Up',
  loading: 'Loading',
  password: 'Password',
  email: 'Email',
  name: 'Name',
  home: 'Home',
  homeMessage: 'Welcome',
  profile: 'Profile',
  profileMessage: 'And this one has a nav, but with a different color than the login.',
  logout: 'Logout',
  forgetPassword:'Forgot Password?',
  signUp:' Don\'t have a Account? Sign Up',
};
